import os
from dotenv import load_dotenv # Assuming you have python-dotenv installed
from services.emailer import send_summary_email

# Load environment variables from .env file (if you use one)
load_dotenv()

# Get credentials from environment variables
# For local testing, ensure these are set in your shell or .env
smtp_user = os.getenv("SMTP_USER")
smtp_password = os.getenv("SMTP_PASSWORD") # This MUST be the Gmail App Password

# Test values
to_email = "veereshkoliwad99@gmail.com" # Use an email you can check
if not to_email:
    to_email = smtp_user # Fallback to sending to self

summary_content = "This is a test summary generated by LexIQ's emailer component. It confirms email functionality."
test_file_id = "test-email-id-123"

print(f"Attempting to send email from: {smtp_user} to: {to_email}")
print(f"Using password: {smtp_password[:4]}...{smtp_password[-4:]} (first/last 4 chars)") # For debug, don't show full password

if not smtp_user or not smtp_password:
    print("❌ ERROR: SMTP_USER or SMTP_PASSWORD environment variables are not set.")
else:
    send_summary_email(to_email, summary_content, test_file_id)